In [122]:
import numpy as np


# Creación de Arrays

In [123]:
array = np.array([i for i in range(10)])
array = np.arange(9) # is the same
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [124]:
array = array.reshape((3,3))
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [125]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [126]:
ones = np.ones((3,2,2))
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

# Operaciones básicas

In [127]:
# suma
arr1 = np.arange(9)
arr2 = np.array([1 for _ in range(9)])
arr1 + arr2


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
ones = np.ones((1,2)).reshape(-1)
twos = np.ones((1,2)).reshape(-1) * 2
result = (ones * twos) / 2
result[1] = 0
print(result.max())
print(result.min())

1.0
0.0


# Slicing

In [129]:
matrix1 = np.random.rand(3,3)
matrix2 = np.random.randint(10, 20, (3,2))
result = matrix1.dot(matrix1)
print(result)
print(result[0:3:2,0:3:2])

[[0.67222806 0.84189307 1.1493239 ]
 [1.02508099 0.83960197 1.393853  ]
 [1.05081418 1.02802002 1.24716941]]
[[0.67222806 1.1493239 ]
 [1.05081418 1.24716941]]


# Manipulación de arrays

In [150]:
# trasponer 
np.random.seed(1)
matrix1 = np.random.randint(1,10, (1,2))
print(matrix1)
print(matrix1.T)
matrix = np.concatenate((matrix1, matrix1),axis=0) # Abajo
print(matrix)
matrix = np.concatenate((matrix1, matrix1),axis=1) # Al lado
print(matrix)

[[6 9]]
[[6]
 [9]]
[[6 9]
 [6 9]]
[[6 9 6 9]]


Latex : HOla $\frac{1}{2}$ $$ 123$$

# Funciones matemáticas

In [130]:
lista  = np.arange(101)
print(lista.mean())
print(lista.std())
print(lista.sum())


50.0
29.154759474226502
5050


In [133]:
lista = np.random.rand(100)
np.cos(lista)

array([0.71893738, 0.69631402, 0.78930527, 0.78927174, 0.98808159,
       0.97041489, 0.78532611, 0.87621788, 0.88466346, 0.71362406,
       0.64228512, 0.97769899, 0.90448194, 0.94891914, 0.83268551,
       0.98538018, 0.96819755, 0.65444032, 0.987418  , 0.97739241,
       0.98434327, 0.85287097, 0.78430082, 0.89281182, 0.65559583,
       0.96378228, 0.97421826, 0.84620692, 0.5981011 , 0.80963492,
       0.78175454, 0.89896524, 0.70930779, 0.86988257, 0.68785016,
       0.69356798, 0.78601006, 0.97183294, 0.63956728, 0.95380971,
       0.82628126, 0.9211458 , 0.683349  , 0.98940206, 0.95658987,
       0.96073903, 0.86922834, 0.78063047, 0.63787284, 0.72338103,
       0.69407829, 0.99480647, 0.96604571, 0.78110629, 0.85330157,
       0.99937917, 0.97245709, 0.65589574, 0.90356746, 0.95652978,
       0.81061075, 0.79633427, 0.80929307, 0.76445438, 0.89431844,
       0.7011077 , 0.67998411, 0.94782481, 0.82295702, 0.96016182,
       0.91913536, 0.98004943, 0.85590228, 0.77413741, 0.68976